name-template: 'Draft for v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
template: |
  ## Changes

  $CHANGES
categories:
  - title: ':rocket: Features'
    labels:
      - 'Enhancement'
      - 'Type: Improvement'
  - title: ':bug: Bug Fixes'
    labels:
      - 'Bug'
      - 'Type: Bug'
  - title: ':toolbox: Maintenance'
    labels:
      - 'Stabilization'
      - 'Topic: Stabilization'
      - 'Type: Chore'
      - 'Type: Refactoring'
  - title: ':books: Documentation'
    labels:
      - 'Category: Doc'
      - 'Documentation'
  - title: ':gear: Logistics'
    labels:
      - 'Category: Build/CI'
      - 'Logistics'      
autolabeler:
  - label: 'Category: Doc'
    title:
      - '/doc/i'
  - label: 'Type: Bug'
    title:
      - '/fix/i'
  - label: 'Type: Improvement'
    title:
      - '/feat/i'
  - label: 'Category: Build/CI'
    title:
      - '/build/i'
      - '/ci/i'
  - label: 'Type: Chore'
    title:
      - '/chore/i'
  - label: 'Type: Refactoring'
    title:
      - '/refactor/i'
