name: Setup Terasology Repo
description: Setup JDK and Gradle for Terasology

runs:
  using: "composite"
  steps:
    - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2