/*
 * Copyright 2013 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.terasology.rendering.world;

import org.lwjgl.opengl.GL11;
import org.terasology.asset.Assets;
import org.terasology.audio.AudioManager;
import org.terasology.config.Config;
import org.terasology.engine.ComponentSystemManager;
import org.terasology.engine.Time;
import org.terasology.engine.subsystem.lwjgl.GLBufferPool;
import org.terasology.entitySystem.entity.EntityManager;
import org.terasology.entitySystem.entity.EntityRef;
import org.terasology.entitySystem.systems.RenderSystem;
import org.terasology.logic.location.LocationComponent;
import org.terasology.logic.players.LocalPlayer;
import org.terasology.logic.players.LocalPlayerSystem;
import org.terasology.math.AABB;
import org.terasology.math.TeraMath;
import org.terasology.math.Vector3i;
import org.terasology.monitoring.PerformanceMonitor;
import org.terasology.physics.bullet.BulletPhysics;
import org.terasology.registry.CoreRegistry;
import org.terasology.rendering.AABBRenderer;
import org.terasology.rendering.RenderHelper;
import org.terasology.rendering.ShaderManager;
import org.terasology.rendering.assets.material.Material;
import org.terasology.rendering.assets.shader.ShaderProgramFeature;
import org.terasology.rendering.cameras.Camera;
import org.terasology.rendering.cameras.OculusStereoCamera;
import org.terasology.rendering.cameras.OrthographicCamera;
import org.terasology.rendering.cameras.PerspectiveCamera;
import org.terasology.rendering.logic.LightComponent;
import org.terasology.rendering.opengl.DefaultRenderingProcess;
import org.terasology.rendering.primitives.ChunkMesh;
import org.terasology.rendering.primitives.LightGeometryHelper;
import org.terasology.world.WorldProvider;
import org.terasology.world.block.Block;
import org.terasology.world.chunks.ChunkConstants;
import org.terasology.world.chunks.ChunkProvider;
import org.terasology.world.chunks.RenderableChunk;

import javax.vecmath.Matrix4f;
import javax.vecmath.Vector3f;

import static org.lwjgl.opengl.GL11.GL_BLEND;
import static org.lwjgl.opengl.GL11.GL_CULL_FACE;
import static org.lwjgl.opengl.GL11.GL_FILL;
import static org.lwjgl.opengl.GL11.GL_FRONT_AND_BACK;
import static org.lwjgl.opengl.GL11.GL_LEQUAL;
import static org.lwjgl.opengl.GL11.GL_LIGHT0;
import static org.lwjgl.opengl.GL11.GL_LINE;
import static org.lwjgl.opengl.GL11.GL_ONE_MINUS_SRC_ALPHA;
import static org.lwjgl.opengl.GL11.GL_SRC_ALPHA;
import static org.lwjgl.opengl.GL11.glBlendFunc;
import static org.lwjgl.opengl.GL11.glCullFace;
import static org.lwjgl.opengl.GL11.glDepthFunc;
import static org.lwjgl.opengl.GL11.glDepthMask;
import static org.lwjgl.opengl.GL11.glDisable;
import static org.lwjgl.opengl.GL11.glEnable;
import static org.lwjgl.opengl.GL11.glLoadIdentity;
import static org.lwjgl.opengl.GL11.glPolygonMode;
import static org.lwjgl.opengl.GL11.glPopMatrix;
import static org.lwjgl.opengl.GL11.glPushMatrix;

/**
 * The world of Terasology. At its most basic the world contains chunks (consisting of a fixed amount of blocks)
 * and the player.
 * <p/>
 * The world is randomly generated by using a bunch of Perlin noise generators initialized
 * with a favored seed value.
 *
 * @author Benjamin Glatzel <benjamin.glatzel@me.com>
 */
public final class WorldRendererLwjgl implements WorldRenderer {
    public static final int VERTICAL_SEGMENTS = CoreRegistry.get(Config.class).getSystem().getVerticalChunkMeshSegments();

    private static final int SHADOW_FRUSTUM_BOUNDS = 500;

    /* WORLD PROVIDER */
    private final WorldProvider worldProvider;

    /* PLAYER */
    private LocalPlayer player;

    /* CAMERA */
    private Camera activeCamera;

    /* SHADOW MAPPING */
    private Camera lightCamera = new OrthographicCamera(-SHADOW_FRUSTUM_BOUNDS, SHADOW_FRUSTUM_BOUNDS, SHADOW_FRUSTUM_BOUNDS, -SHADOW_FRUSTUM_BOUNDS);

    /* LIGHTING */
    // TODO: Review this? (What are we doing with a component not attached to an entity?)
    private LightComponent mainDirectionalLight = new LightComponent();
    private float smoothedPlayerSunlightValue;

    /* RENDERING */
    private RenderQueuesHelper renderQueues;
    private WorldRenderingStage currentRenderingStage = WorldRenderingStage.DEFAULT;

    /* HORIZON */
    private final Skysphere skysphere;

    /* TICKING */
    private Time time = CoreRegistry.get(Time.class);
    private float tick;

    /* PHYSICS */
    // TODO: Remove physics handling from world renderer
    private final BulletPhysics bulletPhysics;

    /* STATISTICS */
    private int statChunkMeshEmpty;
    private int statChunkNotReady;
    private int statRenderedTriangles;

    /* ENUMS */
    public enum ChunkRenderMode {
        DEFAULT,
        REFLECTION,
        SHADOW_MAP,
        Z_PRE_PASS
    }

    private ComponentSystemManager systemManager;
    private Config config;

    private RenderableWorld renderableWorld;

    /**
     * Initializes a new (local) world for the single player mode.
     */
    public WorldRendererLwjgl(WorldProvider worldProvider, ChunkProvider chunkProvider, LocalPlayerSystem localPlayerSystem, GLBufferPool bufferPool) {
        this.worldProvider = worldProvider;
        bulletPhysics = new BulletPhysics(worldProvider);
        skysphere = new Skysphere();

        // TODO: won't need localPlayerSystem here once camera is in the ES proper
        systemManager = CoreRegistry.get(ComponentSystemManager.class);
        Camera localPlayerCamera;
        if (CoreRegistry.get(Config.class).getRendering().isOculusVrSupport()) {
            localPlayerCamera = new OculusStereoCamera();
        } else {
            localPlayerCamera = new PerspectiveCamera(CoreRegistry.get(Config.class).getRendering().getCameraSettings());
        }
        activeCamera = localPlayerCamera;

        mainDirectionalLight.lightType = LightComponent.LightType.DIRECTIONAL;
        mainDirectionalLight.lightColorAmbient = new Vector3f(1.0f, 1.0f, 1.0f);
        mainDirectionalLight.lightColorDiffuse = new Vector3f(1.0f, 1.0f, 1.0f);
        mainDirectionalLight.lightAmbientIntensity = 1.0f;
        mainDirectionalLight.lightDiffuseIntensity = 2.0f;
        mainDirectionalLight.lightSpecularIntensity = 0.0f;

        localPlayerSystem.setPlayerCamera(localPlayerCamera);
        config = CoreRegistry.get(Config.class);

        renderableWorld = new RenderableWorldImpl(worldProvider, chunkProvider, bufferPool, activeCamera, lightCamera);
        renderQueues = renderableWorld.getRenderQueues();
    }


    @Override
    public void onChunkLoaded(Vector3i pos) {
        renderableWorld.onChunkLoaded(pos);
    }

    @Override
    public void onChunkUnloaded(Vector3i pos) {
        renderableWorld.onChunkUnloaded(pos);
    }

    /**
     * @return true if pregeneration is complete
     */
    @Override
    public boolean pregenerateChunks() {
        return renderableWorld.pregenerateChunks();
    }

    @Override
    public void update(float delta) {

        PerformanceMonitor.startActivity("Update Tick");
        updateTick(delta);
        PerformanceMonitor.endActivity();

        if (activeCamera != null) {
            activeCamera.update(delta);
        }

        if (lightCamera != null) {
            positionLightCamera();
            lightCamera.update(delta);
        }

        renderableWorld.update();

        smoothedPlayerSunlightValue = TeraMath.lerp(smoothedPlayerSunlightValue, getSunlightValue(), delta);
    }

    /**
     * Updates the tick variable that animation is based on
     */
    private void updateTick(float delta) {
        tick += delta * 1000;
    }

    private void resetStats() {
        statChunkMeshEmpty = 0;
        statChunkNotReady = 0;
        statRenderedTriangles = 0;
    }

    /**
     * Renders the world.
     */
    @Override
    public void render(DefaultRenderingProcess.StereoRenderState stereoRenderState) {
        switch (stereoRenderState) {
            case MONO:
                currentRenderingStage = WorldRenderingStage.DEFAULT;
                break;
            case OCULUS_LEFT_EYE:
                currentRenderingStage = WorldRenderingStage.OCULUS_LEFT_EYE;
                activeCamera.updateFrustum();
                break;
            case OCULUS_RIGHT_EYE:
                currentRenderingStage = WorldRenderingStage.OCULUS_RIGHT_EYE;
                activeCamera.updateFrustum();
                break;
        }
        resetStats();

        if (stereoRenderState == DefaultRenderingProcess.StereoRenderState.MONO || stereoRenderState == DefaultRenderingProcess.StereoRenderState.OCULUS_LEFT_EYE) {
            renderableWorld.updateAndQueueVisibleChunks();
        } else {
            renderableWorld.updateAndQueueVisibleChunks(false, false);
        }

        if (config.getRendering().isDynamicShadows()
                && (stereoRenderState == DefaultRenderingProcess.StereoRenderState.MONO || stereoRenderState == DefaultRenderingProcess.StereoRenderState.OCULUS_LEFT_EYE)) {
            DefaultRenderingProcess.getInstance().beginRenderSceneShadowMap();
            renderShadowMap(lightCamera);
            DefaultRenderingProcess.getInstance().endRenderSceneShadowMap();
        }

        DefaultRenderingProcess.getInstance().beginRenderReflectedScene();
        glCullFace(GL11.GL_FRONT);
        getActiveCamera().setReflected(true);
        renderWorldReflection(activeCamera);
        getActiveCamera().setReflected(false);
        glCullFace(GL11.GL_BACK);
        DefaultRenderingProcess.getInstance().endRenderReflectedScene();

        renderWorld(getActiveCamera());

        /* COMBINE REFRACTIVE/REFLECTIVE WITH THE OPAQUE SCENE */
        PerformanceMonitor.startActivity("Render Comined Scene");
        DefaultRenderingProcess.getInstance().renderPreCombinedScene();
        PerformanceMonitor.endActivity();

        /* RENDER SIMPLE BLEND MATERIALS INTO THE COMBINED SCENE */
        PerformanceMonitor.startActivity("Render Objects (Transparent)");
        DefaultRenderingProcess.getInstance().beginRenderSceneOpaque();

        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glDepthMask(false);

        for (RenderSystem renderer : systemManager.iterateRenderSubscribers()) {
            renderer.renderAlphaBlend();
        }

        glDisable(GL_BLEND);
        glDepthMask(true);

        DefaultRenderingProcess.getInstance().endRenderSceneOpaque();
        PerformanceMonitor.endActivity();

        /* RENDER THE FINAL POST-PROCESSED SCENE */
        PerformanceMonitor.startActivity("Render Post-Processing");
        DefaultRenderingProcess.getInstance().renderPost(stereoRenderState);
        PerformanceMonitor.endActivity();

        if (activeCamera != null) {
            activeCamera.updatePrevViewProjectionMatrix();
        }
    }

    private void renderShadowMap(Camera camera) {
        PerformanceMonitor.startActivity("Render World (Shadow Map)");

        glDisable(GL_CULL_FACE);

        camera.lookThrough();

        while (renderQueues.chunksOpaqueShadow.size() > 0) {
            renderChunk(renderQueues.chunksOpaqueShadow.poll(), ChunkMesh.RenderPhase.OPAQUE, camera, ChunkRenderMode.SHADOW_MAP);
        }

        for (RenderSystem renderer : systemManager.iterateRenderSubscribers()) {
            renderer.renderShadows();
        }

        glEnable(GL_CULL_FACE);

        PerformanceMonitor.endActivity();
    }

    public void renderWorldReflection(Camera camera) {
        PerformanceMonitor.startActivity("Render World (Reflection)");
        camera.lookThroughNormalized();
        skysphere.render(camera);

        Material chunkShader = Assets.getMaterial("engine:prog.chunk");
        chunkShader.activateFeature(ShaderProgramFeature.FEATURE_USE_FORWARD_LIGHTING);

        if (config.getRendering().isReflectiveWater()) {
            camera.lookThrough();

            glEnable(GL_LIGHT0);

            while (renderQueues.chunksOpaqueReflection.size() > 0) {
                renderChunk(renderQueues.chunksOpaqueReflection.poll(), ChunkMesh.RenderPhase.OPAQUE, camera, ChunkRenderMode.REFLECTION);
            }
        }

        chunkShader.deactivateFeature(ShaderProgramFeature.FEATURE_USE_FORWARD_LIGHTING);
        PerformanceMonitor.endActivity();
    }

    public void renderWorld(Camera camera) {
        if (config.getRendering().getDebug().isWireframe()) {
            glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
        }

        DefaultRenderingProcess.getInstance().clear();
        DefaultRenderingProcess.getInstance().beginRenderSceneOpaque();

        /*
         * SKYSPHERE
         */
        camera.lookThroughNormalized();

        PerformanceMonitor.startActivity("Render Sky");
        DefaultRenderingProcess.getInstance().beginRenderSceneSky();
        skysphere.render(camera);
        DefaultRenderingProcess.getInstance().endRenderSceneSky();
        PerformanceMonitor.endActivity();

        /* WORLD RENDERING */
        PerformanceMonitor.startActivity("Render World");

        camera.lookThrough();
        PerformanceMonitor.startActivity("Render Objects (Opaque)");

        for (RenderSystem renderer : systemManager.iterateRenderSubscribers()) {
            renderer.renderOpaque();
        }
        PerformanceMonitor.endActivity();

        /*
         * FIRST CHUNK PASS: OPAQUE
         */
        PerformanceMonitor.startActivity("Render Chunks (Opaque)");
        while (renderQueues.chunksOpaque.size() > 0) {
            renderChunk(renderQueues.chunksOpaque.poll(), ChunkMesh.RenderPhase.OPAQUE, camera, ChunkRenderMode.DEFAULT);
        }
        PerformanceMonitor.endActivity();

        /*
         * SECOND RENDER PASS: ALPHA REJECT
         */
        PerformanceMonitor.startActivity("Render Chunks (Alpha Reject)");
        while (renderQueues.chunksAlphaReject.size() > 0) {
            renderChunk(renderQueues.chunksAlphaReject.poll(), ChunkMesh.RenderPhase.ALPHA_REJECT, camera, ChunkRenderMode.DEFAULT);
        }
        PerformanceMonitor.endActivity();

        /*
         * OVERLAYS
         */
        PerformanceMonitor.startActivity("Render Overlays");

        for (RenderSystem renderer : systemManager.iterateRenderSubscribers()) {
            renderer.renderOverlay();
        }

        PerformanceMonitor.endActivity();

        /*
         * FIRST PERSON VIEW
         */
        if (activeCamera != null && !config.getRendering().getDebug().isFirstPersonElementsHidden()) {
            PerformanceMonitor.startActivity("Render First Person");

            glPushMatrix();
            glLoadIdentity();

            activeCamera.updateMatrices(90f);
            activeCamera.loadProjectionMatrix();

            glDepthFunc(GL11.GL_ALWAYS);

            for (RenderSystem renderer : systemManager.iterateRenderSubscribers()) {
                renderer.renderFirstPerson();
            }

            glDepthFunc(GL_LEQUAL);

            activeCamera.updateMatrices();
            activeCamera.loadProjectionMatrix();

            glPopMatrix();

            PerformanceMonitor.endActivity();
        }


        DefaultRenderingProcess.getInstance().endRenderSceneOpaque();

        /*
         * LIGHT GEOMETRY (STENCIL) PASS
         */
        PerformanceMonitor.startActivity("Render Light Geometry");

        DefaultRenderingProcess.getInstance().beginRenderLightGeometryStencilPass();
        Material program = Assets.getMaterial("engine:prog.simple");
        program.enable();
        program.setCamera(camera);
        EntityManager entityManager = CoreRegistry.get(EntityManager.class);
        for (EntityRef entity : entityManager.getEntitiesWith(LightComponent.class, LocationComponent.class)) {
            LocationComponent locationComponent = entity.getComponent(LocationComponent.class);
            LightComponent lightComponent = entity.getComponent(LightComponent.class);

            final Vector3f worldPosition = locationComponent.getWorldPosition();
            renderLightComponent(lightComponent, worldPosition, program, camera, true);
        }
        DefaultRenderingProcess.getInstance().endRenderLightGeometryStencilPass();

        /*
         * LIGHT GEOMETRY PASS
         */
        DefaultRenderingProcess.getInstance().beginRenderLightGeometry();
        program = Assets.getMaterial("engine:prog.lightGeometryPass");
        for (EntityRef entity : entityManager.getEntitiesWith(LightComponent.class, LocationComponent.class)) {
            LocationComponent locationComponent = entity.getComponent(LocationComponent.class);
            LightComponent lightComponent = entity.getComponent(LightComponent.class);

            final Vector3f worldPosition = locationComponent.getWorldPosition();
            renderLightComponent(lightComponent, worldPosition, program, camera, false);
        }
        DefaultRenderingProcess.getInstance().endRenderLightGeometry();
        DefaultRenderingProcess.getInstance().beginRenderDirectionalLights();

        // Sunlight
        Vector3f sunlightWorldPosition = new Vector3f(skysphere.getSunDirection(true));
        sunlightWorldPosition.scale(50000f);
        if (activeCamera != null) {
            sunlightWorldPosition.add(activeCamera.getPosition());
        }
        renderLightComponent(mainDirectionalLight, sunlightWorldPosition, program, camera, false);

        DefaultRenderingProcess.getInstance().endRenderDirectionalLights();

        PerformanceMonitor.endActivity();

        /*
        * THIRD CHUNK PASS: REFRACTIVE CHUNKS
        */
        PerformanceMonitor.startActivity("Render Chunks (Refractive/Reflective)");
        DefaultRenderingProcess.getInstance().beginRenderSceneReflectiveRefractive();
        // Make sure the water surface is rendered if the player is swimming
        boolean isHeadUnderWater = isHeadUnderWater();
        if (isHeadUnderWater) {
            glDisable(GL11.GL_CULL_FACE);
        }
        while (renderQueues.chunksAlphaBlend.size() > 0) {
            renderChunk(renderQueues.chunksAlphaBlend.poll(), ChunkMesh.RenderPhase.REFRACTIVE, camera, ChunkRenderMode.DEFAULT);
        }
        PerformanceMonitor.endActivity();
        if (isHeadUnderWater) {
            glEnable(GL11.GL_CULL_FACE);
        }
        PerformanceMonitor.endActivity();
        DefaultRenderingProcess.getInstance().endRenderSceneReflectiveRefractive();

        if (config.getRendering().getDebug().isWireframe()) {
            glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
        }
    }

    private boolean renderLightComponent(LightComponent lightComponent, Vector3f lightWorldPosition, Material program, Camera camera, boolean geometryOnly) {
        Vector3f positionViewSpace = new Vector3f();
        positionViewSpace.sub(lightWorldPosition, activeCamera.getPosition());

        boolean doRenderLight = lightComponent.lightType == LightComponent.LightType.DIRECTIONAL
                || lightComponent.lightRenderingDistance == 0.0f
                || positionViewSpace.lengthSquared() < (lightComponent.lightRenderingDistance * lightComponent.lightRenderingDistance);

        doRenderLight &= isLightVisible(positionViewSpace, lightComponent);

        if (!doRenderLight) {
            return false;
        }

        if (!geometryOnly) {
            if (lightComponent.lightType == LightComponent.LightType.POINT) {
                program.activateFeature(ShaderProgramFeature.FEATURE_LIGHT_POINT);
            } else if (lightComponent.lightType == LightComponent.LightType.DIRECTIONAL) {
                program.activateFeature(ShaderProgramFeature.FEATURE_LIGHT_DIRECTIONAL);
            }
        }
        program.enable();
        program.setCamera(camera);

        Vector3f worldPosition = new Vector3f();
        worldPosition.sub(lightWorldPosition, activeCamera.getPosition());

        Vector3f lightViewPosition = new Vector3f();
        camera.getViewMatrix().transform(worldPosition, lightViewPosition);

        program.setFloat3("lightViewPos", lightViewPosition.x, lightViewPosition.y, lightViewPosition.z, true);

        Matrix4f modelMatrix = new Matrix4f();
        modelMatrix.setIdentity();

        modelMatrix.setTranslation(worldPosition);
        modelMatrix.setScale(lightComponent.lightAttenuationRange);
        program.setMatrix4("modelMatrix", modelMatrix, true);

        if (!geometryOnly) {
            program.setFloat3("lightColorDiffuse", lightComponent.lightColorDiffuse.x, lightComponent.lightColorDiffuse.y, lightComponent.lightColorDiffuse.z, true);
            program.setFloat3("lightColorAmbient", lightComponent.lightColorAmbient.x, lightComponent.lightColorAmbient.y, lightComponent.lightColorAmbient.z, true);

            program.setFloat4("lightProperties", lightComponent.lightAmbientIntensity, lightComponent.lightDiffuseIntensity,
                    lightComponent.lightSpecularIntensity, lightComponent.lightSpecularPower, true);
        }

        if (lightComponent.lightType == LightComponent.LightType.POINT) {
            if (!geometryOnly) {
                program.setFloat4("lightExtendedProperties", lightComponent.lightAttenuationRange * 0.975f, lightComponent.lightAttenuationFalloff, 0.0f, 0.0f, true);
            }

            LightGeometryHelper.renderSphereGeometry();
        } else if (lightComponent.lightType == LightComponent.LightType.DIRECTIONAL) {
            // Directional lights cover all pixels on the screen
            DefaultRenderingProcess.getInstance().renderFullscreenQuad();
        }

        if (!geometryOnly) {
            if (lightComponent.lightType == LightComponent.LightType.POINT) {
                program.deactivateFeature(ShaderProgramFeature.FEATURE_LIGHT_POINT);
            } else if (lightComponent.lightType == LightComponent.LightType.DIRECTIONAL) {
                program.deactivateFeature(ShaderProgramFeature.FEATURE_LIGHT_DIRECTIONAL);
            }
        }

        return true;
    }

    private void renderChunk(RenderableChunk chunk, ChunkMesh.RenderPhase phase, Camera camera, ChunkRenderMode mode) {
        if (chunk.getMesh() != null) {
            Material shader = null;

            final Vector3f cameraPosition = camera.getPosition();
            final Vector3f chunkPositionRelToCamera =
                    new Vector3f(chunk.getPosition().x * ChunkConstants.SIZE_X - cameraPosition.x,
                            chunk.getPosition().y * ChunkConstants.SIZE_Y - cameraPosition.y,
                            chunk.getPosition().z * ChunkConstants.SIZE_Z - cameraPosition.z);

            if (mode == ChunkRenderMode.DEFAULT || mode == ChunkRenderMode.REFLECTION) {
                shader = Assets.getMaterial("engine:prog.chunk");
                shader.enable();

                if (phase == ChunkMesh.RenderPhase.REFRACTIVE) {
                    shader.activateFeature(ShaderProgramFeature.FEATURE_REFRACTIVE_PASS);
                } else if (phase == ChunkMesh.RenderPhase.ALPHA_REJECT) {
                    shader.activateFeature(ShaderProgramFeature.FEATURE_ALPHA_REJECT);
                }

                shader.setFloat3("chunkPositionWorld", chunk.getPosition().x * ChunkConstants.SIZE_X,
                        chunk.getPosition().y * ChunkConstants.SIZE_Y, chunk.getPosition().z * ChunkConstants.SIZE_Z);
                shader.setFloat("animated", chunk.isAnimated() ? 1.0f : 0.0f);

                if (mode == ChunkRenderMode.REFLECTION) {
                    shader.setFloat("clip", camera.getClipHeight());
                } else {
                    shader.setFloat("clip", 0.0f);
                }

            } else if (mode == ChunkRenderMode.SHADOW_MAP) {
                shader = Assets.getMaterial("engine:prog.shadowMap");
                shader.enable();
            } else if (mode == ChunkRenderMode.Z_PRE_PASS) {
                CoreRegistry.get(ShaderManager.class).disableShader();
            }

            GL11.glPushMatrix();

            GL11.glTranslatef(chunkPositionRelToCamera.x, chunkPositionRelToCamera.y, chunkPositionRelToCamera.z);

            for (int i = 0; i < VERTICAL_SEGMENTS; i++) {
                if (!chunk.getMesh()[i].isEmpty()) {
                    if (config.getRendering().getDebug().isRenderChunkBoundingBoxes()) {
                        AABBRenderer aabbRenderer = new AABBRenderer(chunk.getSubMeshAABB(i));
                        aabbRenderer.renderLocally(1f);
                        statRenderedTriangles += 12;
                    }

                    if (shader != null) {
                        shader.enable();
                    }

                    chunk.getMesh()[i].render(phase);
                    statRenderedTriangles += chunk.getMesh()[i].triangleCount();
                }
            }

            if (mode == ChunkRenderMode.DEFAULT || mode == ChunkRenderMode.REFLECTION) {
                // eclipse is paranoid about this - it thinks that shader could be null here
                if (shader != null) {
                    if (phase == ChunkMesh.RenderPhase.REFRACTIVE) {
                        shader.deactivateFeature(ShaderProgramFeature.FEATURE_REFRACTIVE_PASS);
                    } else if (phase == ChunkMesh.RenderPhase.ALPHA_REJECT) {
                        shader.deactivateFeature(ShaderProgramFeature.FEATURE_ALPHA_REJECT);
                    }
                }
            }

            GL11.glPopMatrix();
        } else {
            statChunkNotReady++;
        }
    }

    public void positionLightCamera() {
        // Shadows are rendered around the player so...
        Vector3f lightPosition = new Vector3f(activeCamera.getPosition().x, 0.0f, activeCamera.getPosition().z);

        // Project the camera position to light space and make sure it is only moved in texel steps (avoids flickering when moving the camera)
        float texelSize = 1.0f / config.getRendering().getShadowMapResolution();
        texelSize *= 2.0f;

        lightCamera.getViewProjectionMatrix().transform(lightPosition);
        lightPosition.set(TeraMath.fastFloor(lightPosition.x / texelSize) * texelSize, 0.0f, TeraMath.fastFloor(lightPosition.z / texelSize) * texelSize);
        lightCamera.getInverseViewProjectionMatrix().transform(lightPosition);

        // ... we position our new camera at the position of the player and move it
        // quite a bit into the direction of the sun (our main light).

        // Make sure the sun does not move too often since it causes massive shadow flickering (from hell to the max)!
        float stepSize = 50f;
        Vector3f sunDirection = skysphere.getQuantizedSunDirection(stepSize);

        Vector3f sunPosition = new Vector3f(sunDirection);
        sunPosition.scale(256.0f + 64.0f);
        lightPosition.add(sunPosition);

        lightCamera.getPosition().set(lightPosition);

        // and adjust it to look from the sun direction into the direction of our player
        Vector3f negSunDirection = new Vector3f(sunDirection);
        negSunDirection.scale(-1.0f);

        lightCamera.getViewingDirection().set(negSunDirection);
    }

    /**
     * Disposes this world.
     */
    @Override
    public void dispose() {
        renderableWorld.dispose();
        worldProvider.dispose();
        CoreRegistry.get(AudioManager.class).stopAllSounds();
    }

    /**
     * Sets a new player and spawns him at the spawning point.
     *
     * @param p The player
     */
    @Override
    public void setPlayer(LocalPlayer p) {
        player = p;
        renderableWorld.updateChunksInProximity(config.getRendering().getViewDistance());
    }

    @Override
    public void changeViewDistance(ViewDistance viewingDistance) {
        renderableWorld.updateChunksInProximity(viewingDistance);
    }

    public boolean isAABBVisible(Camera cam, AABB aabb) {
        return cam.getViewFrustum().intersects(aabb);
    }

    @Override
    public boolean isAABBVisible(AABB aabb) {
        return isAABBVisible(activeCamera, aabb);
    }

    public boolean isLightVisible(Vector3f positionViewSpace, LightComponent component) {
        return component.lightType == LightComponent.LightType.DIRECTIONAL
                || activeCamera.getViewFrustum().intersects(positionViewSpace, component.lightAttenuationRange);

    }

    public boolean isHeadUnderWater() {
        Vector3f cameraPos = new Vector3f(CoreRegistry.get(WorldRenderer.class).getActiveCamera().getPosition());

        // Compensate for waves
        if (config.getRendering().isAnimateWater()) {
            cameraPos.y -= RenderHelper.evaluateOceanHeightAtPosition(cameraPos, worldProvider.getTime().getDays());
        }

        if (worldProvider.isBlockRelevant(new Vector3f(cameraPos))) {
            Block block = worldProvider.getBlock(new Vector3f(cameraPos));
            return block.isLiquid();
        }
        return false;
    }

    @Override
    public float getSmoothedPlayerSunlightValue() {
        return smoothedPlayerSunlightValue;
    }

    @Override
    public float getSunlightValue() {
        return getSunlightValueAt(new Vector3f(getActiveCamera().getPosition()));
    }

    @Override
    public float getBlockLightValue() {
        return getBlockLightValueAt(new Vector3f(getActiveCamera().getPosition()));
    }

    @Override
    public float getRenderingLightValueAt(Vector3f pos) {
        float rawLightValueSun = worldProvider.getSunlight(pos) / 15.0f;
        float rawLightValueBlock = worldProvider.getLight(pos) / 15.0f;

        float lightValueSun = (float) Math.pow(BLOCK_LIGHT_SUN_POW, (1.0f - rawLightValueSun) * 16.0f) * rawLightValueSun;
        lightValueSun *= getDaylight();
        // TODO: Hardcoded factor and value to compensate for daylight tint and night brightness
        lightValueSun *= 0.9f;
        lightValueSun += 0.05f;

        float lightValueBlock = (float) Math.pow(BLOCK_LIGHT_POW, (1.0f - rawLightValueBlock) * 16.0f) * rawLightValueBlock * BLOCK_INTENSITY_FACTOR;

        return Math.max(lightValueBlock, lightValueSun);
    }

    @Override
    public float getSunlightValueAt(Vector3f pos) {
        float sunlight = worldProvider.getSunlight(pos) / 15.0f;
        sunlight *= getDaylight();

        return sunlight;
    }

    @Override
    public float getBlockLightValueAt(Vector3f pos) {
        return worldProvider.getLight(pos) / 15.0f;
    }

    @Override
    public String getMetrics() {
        StringBuilder builder = new StringBuilder();
        builder.append(renderableWorld.getMetrics());
        builder.append("Empty Mesh Chunks: ");
        builder.append(statChunkMeshEmpty);
        builder.append("\n");
        builder.append("Unready Chunks: ");
        builder.append(statChunkNotReady);
        builder.append("\n");
        builder.append("Rendered Triangles: ");
        builder.append(statRenderedTriangles);
        builder.append("\n");
        return builder.toString();
    }

    public LocalPlayer getPlayer() {
        return player;
    }

    @Override
    public float getDaylight() {
        return skysphere.getDaylight();
    }

    @Override
    public WorldProvider getWorldProvider() {
        return worldProvider;
    }

    @Override
    public ChunkProvider getChunkProvider() {
        return renderableWorld.getChunkProvider();
    }

    @Override
    public Skysphere getSkysphere() {
        return skysphere;
    }

    public Time getTime() {
        return time;
    }

    @Override
    public float getTick() {
        return tick;
    }


    @Override
    public BulletPhysics getBulletRenderer() {
        return bulletPhysics;
    }

    @Override
    public Camera getActiveCamera() {
        return activeCamera;
    }

    @Override
    public Camera getLightCamera() {
        return lightCamera;
    }

    @Override
    public WorldRenderingStage getCurrentRenderStage() {
        return currentRenderingStage;
    }

    @Override
    public Vector3f getTint() {
        Vector3f cameraPos = getActiveCamera().getPosition();
        Block block = worldProvider.getBlock(cameraPos);
        return block.getTint();
    }
}
