/*
 * Copyright 2017 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 22 21:26:48 GMT 2017
 */

package org.terasology.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Locale;
import org.junit.runner.RunWith;
import org.terasology.config.SystemConfig;


public class SystemConfig_ESTest{

  @Test(timeout = 4000)
  public void testSystemConfigIsWriteSaveGamesEnabled1()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setWriteSaveGamesEnabled(true);
      boolean boolean0 = systemConfig0.isWriteSaveGamesEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigIsMonitoringEnabled1()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMonitoringEnabled(true);
      boolean boolean0 = systemConfig0.isMonitoringEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigIsDebugEnabled1()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setDebugEnabled(true);
      boolean boolean0 = systemConfig0.isDebugEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetMaxUnloadedChunksPercentageTillSave()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMaxUnloadedChunksPercentageTillSave(2745);
      int int0 = systemConfig0.getMaxUnloadedChunksPercentageTillSave();
      assertEquals(2745, int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetMaxUnloadedCHunksPercentageTillSave()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMaxUnloadedChunksPercentageTillSave((800));
      int int0 = systemConfig0.getMaxUnloadedChunksPercentageTillSave();
      assertEquals((800), int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigSetMaxThreads()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMaxThreads(1);
      int int0 = systemConfig0.getMaxThreads();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigSetMaxSecondsBetweenSaves()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMaxSecondsBetweenSaves(1);
      int int0 = systemConfig0.getMaxSecondsBetweenSaves();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetMaxSecondsBetweenSaves()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMaxSecondsBetweenSaves((642));
      int int0 = systemConfig0.getMaxSecondsBetweenSaves();
      assertEquals((642), int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigSetDayNightLengthInMs()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setDayNightLengthInMs(215L);
      long long0 = systemConfig0.getDayNightLengthInMs();
      assertEquals(215L, long0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigSetDayNightLengthInMsNegative()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setDayNightLengthInMs((-117L));
      long long0 = systemConfig0.getDayNightLengthInMs();
      assertEquals((-117L), long0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigSetLocaleNull()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      // Undeclared exception!
      try { 
        systemConfig0.setLocale((Locale) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //assertThrownBy("org.terasology.config.SystemConfig", e);
      }
  }

  @Test(timeout = 4000)
  public void testSystemConfigIsWriteSaveGamesEnabled2()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      boolean boolean0 = systemConfig0.isWriteSaveGamesEnabled();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigSetMaxThreadsNegative()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      systemConfig0.setMaxThreads((-1));
      int int0 = systemConfig0.getMaxThreads();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigIsMonitoringEnabled2()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      boolean boolean0 = systemConfig0.isMonitoringEnabled();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetMaxThreads()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      int int0 = systemConfig0.getMaxThreads();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigIsDebugEnabled2()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      boolean boolean0 = systemConfig0.isDebugEnabled();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetMaxSecondsBetweenSavesDefault()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      int int0 = systemConfig0.getMaxSecondsBetweenSaves();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetMaxUnloadedChunksPercentageTillSaveDefault()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      int int0 = systemConfig0.getMaxUnloadedChunksPercentageTillSave();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void testSystemConfigGetDayNightLengthInMsDefault()  throws Throwable  {
      SystemConfig systemConfig0 = new SystemConfig();
      long long0 = systemConfig0.getDayNightLengthInMs();
      assertEquals(0L, long0);
  }
}
